### ISSUE TITLE
Memory warnings in SPAN Galaxy plugin with default options

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/galaxy-applications#8]
SPAN log using Galaxy plugin with default options contains the warning:

```
[Nov 26, 2018 10:08:50 WARN SpanCLA] Recommended memory settings 4 gb are not set. Current settings: 1,8 gb.
Please use java memory option '-Xmx4G' to configure memory available for SPAN.
```

**Comment by iromeo** [comment]
Also, I'm not sure that "2GB" default is enough and won't result in infinite GC for real data. At least our aging data required more than 3 gb for 4 threads.

**Comment by iromeo** [comment]
GSE112622 rna-seq data fits 2GB, 2 threads

**Comment by olegs** [comment]
@iromeo after all, do you think we should increase default Xmx to 4G for galaxy application?

**Comment by iromeo** [comment]
I think the best option is to estimate how much RAM we need depending on threads number. I cannot say how much RAM do we need for 2 threads. I think default options shouldn't result in OOM or infinite GC and better to make them not very strict. AFAIU there is no big difference for Galaxy whether to use 2G or 4G.

**Comment by olegs** [comment]
Estimating exact RAM quantity is not an easy and robust task, depending on genome length, reads numbers, etc. Increasing to 4G to avoid any warnings will work here.

**Comment by iromeo** [comment]
ok

**Comment by iromeo** [comment]
1g isn't enough for 1 (or 2) threads and GSE112622  (SRR6929777_CAST_EiJ_rep3993_mm9.bam file)
